### ISSUE TITLE
Black Theme for Website

### ISSUE THREAD

**Issue by sainanda59** [sainanda59/portfolio_react#2]
Toggle Switch for Theme change

**Comment by arpanaditya** [comment]
Hey @sainanda59 can I work on this issue? you just have to provide me with your desired colors for the dark theme.

**Comment by sainanda59** [comment]
@arpanaditya Sure, buddy. Go ahead, and there is no such bound. Let your creativity out.

**Comment by arpanaditya** [comment]
Please assign this issue to me

**Comment by sainanda59** [comment]
Assigned you @arpanaditya. Good Luck
